---
title: "4.2.4"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(readr)
library(knitr)
grocery_data<-read.csv("survey_data.csv", header=TRUE)

grocery_data<-grocery_data %>% rename(
  Store = Q1, 
  Other_Store = Q2, 
  Produce = Q3_1, 
  Dairy = Q3_2, 
  Grain = Q3_3, 
  Baking = Q3_4, 
  Drinks = Q3_5, 
  Protein = Q3_6, 
  Freq_Dineout = Q1.1, 
  Resturant = Q2.1, 
  Other_Resturant = Q3, 
  Koko = Q4_1, 
  WingsOver = Q4_2, 
  Moosewood = Q4_3, 
  ThompsonBleeker = Q4_4, 
  Pokelava = Q4_5, 
  Appetizers = Q5_1, 
  Entrees = Q5_2, 
  Desserts = Q5_3, 
  Beverages = Q5_4)


grocery_data <- grocery_data[-c(1, 2), ] %>%
  select(-(1:11)) %>%
  filter(!is.na(Store) & Store != "")

grocery_data <- grocery_data %>%
  mutate(across(c("Produce", "Dairy", "Grain", "Baking", "Drinks", "Protein", "Appetizers", "Entrees", "Desserts", "Beverages"), ~ ifelse(. == "", 0, .))) %>% 
  mutate(across(c("Produce", "Dairy", "Grain", "Baking", "Drinks", "Protein","Appetizers", "Entrees", "Desserts", "Beverages"), as.numeric))



grocery_data <- grocery_data %>%
  mutate(Weekly_Grocery_Total = rowSums(across(c("Produce", "Dairy", "Grain", "Baking", "Drinks", "Protein")), na.rm = TRUE)) %>%
   mutate(Weekly_Dineout_Total = rowSums(across(c("Appetizers", "Entrees", "Desserts", "Beverages")), na.rm = TRUE)) %>%
  mutate(Weekly_Total = rowSums(across(c("Weekly_Grocery_Total", "Weekly_Dineout_Total")), na.rm = TRUE))



```

```{r}
grocery_data<-grocery_data%>% 
  mutate(week = row_number()) |>
  filter(Store != "")
```

```{r}

library("ggplot2")
library(scales)

lineGraph_Data <- grocery_data %>% 
  mutate(week = row_number())

ggplot(lineGraph_Data, aes(x = week, y = Weekly_Total)) +
  geom_line(color = "red") + 
  geom_point(color = "blue") + 
  labs(
    title = "Spending Trend For The Month Of November", 
    x = "Days In November", 
    y = "Total Spent (in USD)"
  ) +
  scale_y_continuous(labels = dollar) +
  theme_minimal()
  
```
